# Generated by Django 6.0.3 on 2026-03-26 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Нэр')),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('photo', models.ImageField(upload_to='anket/5b149aecf0724f59a1d0be46926fa9de')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Нэр')),
                ('last_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Овог')),
                ('email', models.CharField(blank=True, max_length=500, null=True, verbose_name='Имэйл хаяг')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Даалгаврын нэр')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Даалгаврын эцсийн хугацаа')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Хийх'), (1, 'Хийж буй'), (2, 'Хийж дууссан')], null=True, verbose_name='Даалгаврийн төлөв')),
                ('priority', models.IntegerField(blank=True, choices=[(0, 'Энгийн'), (1, 'Яаралтай')], null=True, verbose_name='Даалгаврийн priority')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Даалгавар үүссэн огноо')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='Даалгавар шинэчилсэн огноо')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
