# Generated by Django 6.0.3 on 2026-03-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='anket/b706ad841acc46659a70379b4ec72eb4'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
