# Generated by Django 6.0.3 on 2026-03-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_image_photo_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='anket/22c9aad83f6e4f25b92aea6a67b7621c'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Даалгавар үүссэн огноо'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Даалгавар шинэчилсэн огноо'),
        ),
    ]
